// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NumberingClient is the client API for Numbering service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NumberingClient interface {
	//Adds a new unused number to database.
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
	//Not implemented
	AddGroup(ctx context.Context, in *AddGroupRequest, opts ...grpc.CallOption) (*AddGroupResponse, error)
	//List returns a filtered list of numbers
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	//ListOwnerID gets list of numbers attached to specific OwnerID
	ListOwnerID(ctx context.Context, in *ListOwnerIDRequest, opts ...grpc.CallOption) (*ListOwnerIDResponse, error)
	//Reserve locks a number to a OwnerID until untilTS (unix timestamp)
	Reserve(ctx context.Context, in *ReserveRequest, opts ...grpc.CallOption) (*ReserveResponse, error)
	//Allocate marks a number 'used' by a
	Allocate(ctx context.Context, in *AllocateRequest, opts ...grpc.CallOption) (*AllocateResponse, error)
	//DeAllocate number from User (number goes to quarantine)
	DeAllocate(ctx context.Context, in *DeAllocateRequest, opts ...grpc.CallOption) (*DeAllocateResponse, error)
	//Portout sets a port out date (just a log, doesn't care about state or do anything else)
	Portout(ctx context.Context, in *PortoutRequest, opts ...grpc.CallOption) (*PortoutResponse, error)
	//Portin sets a port in date (just a log, doesn't care about state or do anything else)
	Portin(ctx context.Context, in *PortinRequest, opts ...grpc.CallOption) (*PortinResponse, error)
	//Delete - number no longer used, removed from number db, must be unused (history kept).
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	//View formatted table of details for a specific number (with history).
	View(ctx context.Context, in *ViewRequest, opts ...grpc.CallOption) (*ViewResponse, error)
	//Summary formatted table of usage stats
	Summary(ctx context.Context, in *SummaryRequest, opts ...grpc.CallOption) (*SummaryResponse, error)
}

type numberingClient struct {
	cc grpc.ClientConnInterface
}

func NewNumberingClient(cc grpc.ClientConnInterface) NumberingClient {
	return &numberingClient{cc}
}

func (c *numberingClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, "/grpc.Numbering/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *numberingClient) AddGroup(ctx context.Context, in *AddGroupRequest, opts ...grpc.CallOption) (*AddGroupResponse, error) {
	out := new(AddGroupResponse)
	err := c.cc.Invoke(ctx, "/grpc.Numbering/AddGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *numberingClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/grpc.Numbering/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *numberingClient) ListOwnerID(ctx context.Context, in *ListOwnerIDRequest, opts ...grpc.CallOption) (*ListOwnerIDResponse, error) {
	out := new(ListOwnerIDResponse)
	err := c.cc.Invoke(ctx, "/grpc.Numbering/ListOwnerID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *numberingClient) Reserve(ctx context.Context, in *ReserveRequest, opts ...grpc.CallOption) (*ReserveResponse, error) {
	out := new(ReserveResponse)
	err := c.cc.Invoke(ctx, "/grpc.Numbering/Reserve", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *numberingClient) Allocate(ctx context.Context, in *AllocateRequest, opts ...grpc.CallOption) (*AllocateResponse, error) {
	out := new(AllocateResponse)
	err := c.cc.Invoke(ctx, "/grpc.Numbering/Allocate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *numberingClient) DeAllocate(ctx context.Context, in *DeAllocateRequest, opts ...grpc.CallOption) (*DeAllocateResponse, error) {
	out := new(DeAllocateResponse)
	err := c.cc.Invoke(ctx, "/grpc.Numbering/DeAllocate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *numberingClient) Portout(ctx context.Context, in *PortoutRequest, opts ...grpc.CallOption) (*PortoutResponse, error) {
	out := new(PortoutResponse)
	err := c.cc.Invoke(ctx, "/grpc.Numbering/Portout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *numberingClient) Portin(ctx context.Context, in *PortinRequest, opts ...grpc.CallOption) (*PortinResponse, error) {
	out := new(PortinResponse)
	err := c.cc.Invoke(ctx, "/grpc.Numbering/Portin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *numberingClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/grpc.Numbering/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *numberingClient) View(ctx context.Context, in *ViewRequest, opts ...grpc.CallOption) (*ViewResponse, error) {
	out := new(ViewResponse)
	err := c.cc.Invoke(ctx, "/grpc.Numbering/View", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *numberingClient) Summary(ctx context.Context, in *SummaryRequest, opts ...grpc.CallOption) (*SummaryResponse, error) {
	out := new(SummaryResponse)
	err := c.cc.Invoke(ctx, "/grpc.Numbering/Summary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NumberingServer is the server API for Numbering service.
// All implementations must embed UnimplementedNumberingServer
// for forward compatibility
type NumberingServer interface {
	//Adds a new unused number to database.
	Add(context.Context, *AddRequest) (*AddResponse, error)
	//Not implemented
	AddGroup(context.Context, *AddGroupRequest) (*AddGroupResponse, error)
	//List returns a filtered list of numbers
	List(context.Context, *ListRequest) (*ListResponse, error)
	//ListOwnerID gets list of numbers attached to specific OwnerID
	ListOwnerID(context.Context, *ListOwnerIDRequest) (*ListOwnerIDResponse, error)
	//Reserve locks a number to a OwnerID until untilTS (unix timestamp)
	Reserve(context.Context, *ReserveRequest) (*ReserveResponse, error)
	//Allocate marks a number 'used' by a
	Allocate(context.Context, *AllocateRequest) (*AllocateResponse, error)
	//DeAllocate number from User (number goes to quarantine)
	DeAllocate(context.Context, *DeAllocateRequest) (*DeAllocateResponse, error)
	//Portout sets a port out date (just a log, doesn't care about state or do anything else)
	Portout(context.Context, *PortoutRequest) (*PortoutResponse, error)
	//Portin sets a port in date (just a log, doesn't care about state or do anything else)
	Portin(context.Context, *PortinRequest) (*PortinResponse, error)
	//Delete - number no longer used, removed from number db, must be unused (history kept).
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	//View formatted table of details for a specific number (with history).
	View(context.Context, *ViewRequest) (*ViewResponse, error)
	//Summary formatted table of usage stats
	Summary(context.Context, *SummaryRequest) (*SummaryResponse, error)
	mustEmbedUnimplementedNumberingServer()
}

// UnimplementedNumberingServer must be embedded to have forward compatible implementations.
type UnimplementedNumberingServer struct {
}

func (UnimplementedNumberingServer) Add(context.Context, *AddRequest) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedNumberingServer) AddGroup(context.Context, *AddGroupRequest) (*AddGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddGroup not implemented")
}
func (UnimplementedNumberingServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedNumberingServer) ListOwnerID(context.Context, *ListOwnerIDRequest) (*ListOwnerIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOwnerID not implemented")
}
func (UnimplementedNumberingServer) Reserve(context.Context, *ReserveRequest) (*ReserveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reserve not implemented")
}
func (UnimplementedNumberingServer) Allocate(context.Context, *AllocateRequest) (*AllocateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Allocate not implemented")
}
func (UnimplementedNumberingServer) DeAllocate(context.Context, *DeAllocateRequest) (*DeAllocateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeAllocate not implemented")
}
func (UnimplementedNumberingServer) Portout(context.Context, *PortoutRequest) (*PortoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Portout not implemented")
}
func (UnimplementedNumberingServer) Portin(context.Context, *PortinRequest) (*PortinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Portin not implemented")
}
func (UnimplementedNumberingServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedNumberingServer) View(context.Context, *ViewRequest) (*ViewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method View not implemented")
}
func (UnimplementedNumberingServer) Summary(context.Context, *SummaryRequest) (*SummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Summary not implemented")
}
func (UnimplementedNumberingServer) mustEmbedUnimplementedNumberingServer() {}

// UnsafeNumberingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NumberingServer will
// result in compilation errors.
type UnsafeNumberingServer interface {
	mustEmbedUnimplementedNumberingServer()
}

func RegisterNumberingServer(s grpc.ServiceRegistrar, srv NumberingServer) {
	s.RegisterService(&Numbering_ServiceDesc, srv)
}

func _Numbering_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NumberingServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Numbering/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NumberingServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Numbering_AddGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NumberingServer).AddGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Numbering/AddGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NumberingServer).AddGroup(ctx, req.(*AddGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Numbering_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NumberingServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Numbering/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NumberingServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Numbering_ListOwnerID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOwnerIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NumberingServer).ListOwnerID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Numbering/ListOwnerID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NumberingServer).ListOwnerID(ctx, req.(*ListOwnerIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Numbering_Reserve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NumberingServer).Reserve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Numbering/Reserve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NumberingServer).Reserve(ctx, req.(*ReserveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Numbering_Allocate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NumberingServer).Allocate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Numbering/Allocate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NumberingServer).Allocate(ctx, req.(*AllocateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Numbering_DeAllocate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeAllocateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NumberingServer).DeAllocate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Numbering/DeAllocate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NumberingServer).DeAllocate(ctx, req.(*DeAllocateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Numbering_Portout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PortoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NumberingServer).Portout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Numbering/Portout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NumberingServer).Portout(ctx, req.(*PortoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Numbering_Portin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PortinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NumberingServer).Portin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Numbering/Portin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NumberingServer).Portin(ctx, req.(*PortinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Numbering_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NumberingServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Numbering/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NumberingServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Numbering_View_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NumberingServer).View(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Numbering/View",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NumberingServer).View(ctx, req.(*ViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Numbering_Summary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NumberingServer).Summary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Numbering/Summary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NumberingServer).Summary(ctx, req.(*SummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Numbering_ServiceDesc is the grpc.ServiceDesc for Numbering service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Numbering_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Numbering",
	HandlerType: (*NumberingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Numbering_Add_Handler,
		},
		{
			MethodName: "AddGroup",
			Handler:    _Numbering_AddGroup_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Numbering_List_Handler,
		},
		{
			MethodName: "ListOwnerID",
			Handler:    _Numbering_ListOwnerID_Handler,
		},
		{
			MethodName: "Reserve",
			Handler:    _Numbering_Reserve_Handler,
		},
		{
			MethodName: "Allocate",
			Handler:    _Numbering_Allocate_Handler,
		},
		{
			MethodName: "DeAllocate",
			Handler:    _Numbering_DeAllocate_Handler,
		},
		{
			MethodName: "Portout",
			Handler:    _Numbering_Portout_Handler,
		},
		{
			MethodName: "Portin",
			Handler:    _Numbering_Portin_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Numbering_Delete_Handler,
		},
		{
			MethodName: "View",
			Handler:    _Numbering_View_Handler,
		},
		{
			MethodName: "Summary",
			Handler:    _Numbering_Summary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "numbering.proto",
}
